language: node_js
node_js:
  - "5.6"
  - "4.1"

addons:
    code_climate:
        repo_token: c418b3b6e97008be50161f0ee83af18df8779d60d0afcbc3cf22c042f2e488e3
        

after_script:
  - codeclimate-test-reporter < lcov.info
